FROM luma-base AS worker
WORKDIR /workspace/apps/worker
RUN /workspace/packages/storage/node_modules/.bin/prisma generate --schema=/workspace/packages/storage/prisma/schema.prisma
CMD ["pnpm", "start"]