FROM luma-base AS worker
WORKDIR /workspace/apps/worker
# Copy entire @prisma+client package and .prisma folder
RUN cp -r /workspace/.prisma-app /workspace/node_modules/.prisma && \
    cp -r /workspace/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0 /workspace/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0
CMD ["pnpm", "start"]